platform :ios, '5.0'
pod 'ReactiveCocoa', '~>2.1.1'
pod 'libextobjc', '~>0.3'
pod 'BZGMailgunEmailValidation', '~>1.0.0'

target :SignupFormTests do
    pod 'Expecta', '~>0.2.2'
    pod 'OCMockito', '~>1.0.0'
end