platform :ios, '5.0'

pod 'BZGMailgunEmailValidation'

# BZGFormViewController
pod 'ReactiveCocoa', '~>2.3'
pod 'libextobjc', '~>0.4'
pod 'libPhoneNumber-iOS', '~>0.7'

target :SignupFormTests do
    pod 'Specta', '~>0.2.1'
    pod 'Expecta', '~>0.3.0'
    pod 'OCMockito', '~>1.1.0'
    pod 'OCMock', '~>2.2.3'
end
